name: CI Workflow - Install, Test, Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_test_build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js for backend
      - name: Set up Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Change the version based on your project needs

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./api
        run: npm install

      # Run backend tests
      - name: Run backend tests
        working-directory: ./api
        run: npm test
          
          

      # Build the backend application (if applicable, e.g., compiling TypeScript)
      - name: Build backend application
        working-directory: ./api
        run:  npm run build  # Adjust the command if necessary for your build setup

          
         
      # Set up Node.js for frontend
      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Same as backend, or different if necessary

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./webapp
        run: npm install
          
         

      # Run frontend tests
      - name: Run frontend tests
        working-directory: ./webapp
        run: npm run test  # This could be "npx cypress run" if using Cypress
          
          

      # Build the frontend application (e.g., for React, Vue, etc.)
      - name: Build frontend application
        working-directory: ./webapp
        run: npm run build  # Adjust this if you have a different build script (e.g., `react-scripts build`)
          
          
