name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js for both backend and frontend
      - name: Set up Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change the Node.js version based on your project

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd api
          npm install

      # Set up Node.js for frontend
      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change the Node.js version based on your project

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd webapp
          npm install
